version: "3"

services:
  go-server:
    container_name: go-server
    build: "./server"
    expose:
      - "8000"
    environment:
      DB_URL: host.docker.internal:3309
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    container_name: react-nginx
    build: "."
    ports:
      - "80:80"
    depends_on:
      - "go-server"
