version: "3"

services:
  db:
    container_name: db
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypw
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./mysql/database:/var/lib/mysql"
  go-server:
    container_name: go-server
    image: go-server:latest
    expose:
      - "8000"
    environment:
      DB_URL: db:3306
    depends_on:
      - "db"