version: "3"

networks:
  net: {}

services:
  db:
    container_name: db
    #    build: "."
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypw
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./mysql/database:/var/lib/mysql"