FROM golang:1.18 as builder
ENV GOOS linux
ENV CGO_ENABLED 0
WORKDIR /app
COPY . .
RUN go build -o app
FROM alpine:3.14
# Add certificates
RUN apk add --no-cache ca-certificates
# Copy built binary from builder
COPY --from=builder app .
# Expose port
EXPOSE 8000
# Exec built binary
CMD ./app